config/routes.rb
Electune::Application.routes.draw do

  root :to => 'playlists#show', :id => '1'

  resources :users
  resources :sessions, only: [:create, :destroy]
  resources :playlists do
    get 'current', on: :member
    resources :playlist_items, :only => [:create]
  end

  match "/search" => "playlist_items#index", as: "search", via: :post
  match "/artist_lookup" => "playlist_items#artist_lookup", as: "artist_lookup", via: :get
  match "/album_lookup" => "playlist_items#album_lookup", as: "album_lookup", via: :get

  match "/playlist_items/upvote/:id" => "playlist_items#upvote", as: "upvote", via: :post
  match "/playlist_items/veto/:id" => "playlist_items#veto", as: "veto", via: :post

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/user.rb
class User < ActiveRecord::Base

  extend ActiveRandom

  has_secure_password
  attr_accessible :email, :password, :password_confirmation

  has_many :upvotements, foreign_key: "upvoter_id", dependent: :destroy
  has_many :upvoted_playlist_items, through: :upvotements, source: :playlist_item
  has_many :vetoments, foreign_key: "vetoer_id", dependent: :destroy
  has_many :vetoed_playlist_items, through: :vetoments, source: :playlist_item

  before_save { self.email.downcase! }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :signed_in_user, only: [:destroy, :index, :edit, :update]
  before_filter :correct_user, only: [:destroy, :edit, :update]
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html do
          sign_in @user
          redirect_back_or @user
          flash[:notice] = "logged in successfully."
        end
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(signin_path) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit "Create User", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% title "Edit User" %>
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'View User', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% title 'User List' %>

<h1>Listing users</h1>

<table class="table table-striped">
  <tr>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) unless session[:user_id] != user.id %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } unless session[:user_id] != user.id %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% title 'New User' %>

<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% title 'User Profile' %>
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>