config/routes.rb
Electune::Application.routes.draw do

  root :to => 'playlists#show', :id => '1'

  resources :users
  resources :sessions, only: [:create, :destroy]
  resources :playlists do
    get 'current', on: :member
    resources :playlist_items, :only => [:create]
  end

  match "/search" => "playlist_items#index", as: "search", via: :post
  match "/artist_lookup" => "playlist_items#artist_lookup", as: "artist_lookup", via: :get
  match "/album_lookup" => "playlist_items#album_lookup", as: "album_lookup", via: :get

  match "/playlist_items/upvote/:id" => "playlist_items#upvote", as: "upvote", via: :post
  match "/playlist_items/veto/:id" => "playlist_items#veto", as: "veto", via: :post

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/playlist_item.rb
class PlaylistItem < ActiveRecord::Base

  belongs_to :playlist
  has_many :upvotements, dependent: :destroy
  has_many :upvoters, through: :upvotements, source: :upvoter
  has_many :vetoments, dependent: :destroy
  has_many :vetoers, through: :vetoments, source: :vetoer
  belongs_to :song
  belongs_to :user


  attr_accessible :song, :user

  after_create :default_values

  def default_values
    self.upvote self.user.id
  end

  def already_upvoted_by_user? user_id
    user = User.find user_id
    upvoters.include? user
  end

  def already_vetoed_by_user? user_id
    user = User.find user_id
    vetoers.include? user
  end

  def votes
   upvotements.count - vetoments.count
  end

  def upvote user_id
    upvotements.find_or_create_by_upvoter_id(user_id)
  end

  def veto user_id
    vetoments.find_or_create_by_vetoer_id(user_id) unless self.votes <= 0
    checkremove
  end

  private
    def checkremove
      if votes == 0
        self.playlist.delete self unless self.playlist.nil?
      end
    end
end

app/controllers/playlist_items_controller.rb
class PlaylistItemsController < ApplicationController

  before_filter :signed_in_user

  def index
    @playlist = Playlist.find(params[:playlist_id])
    if params[:search].present?
      begin
        @playlist_items = SpotifySongSearch.perform_search(params[:search])
      rescue OpenURI::HTTPError => e
        render :action => "service_error"
      end
    elsif params[:artist].present?
      begin
        @artists = SpotifySongSearch.perform_search_by_artist(params[:artist])
        render :action => "artist"
      rescue OpenURI::HTTPError => e
        render :action => "service_error"
      end
    end
  end

  def artist_lookup
    @playlist = Playlist.find(params[:playlist_id])
    begin
      @albums = SpotifySongSearch.perform_lookup_by_artist(params[:spotify_link])
    rescue OpenURI::HTTPError => e
        render :action => "service_error"
    end
  end

  def album_lookup
    @playlist = Playlist.find(params[:playlist_id])
    begin
      @playlist_items = SpotifySongSearch.perform_lookup_by_album(params[:spotify_link])
      render :action => "index"
    rescue OpenURI::HTTPError => e
        render :action => "service_error"
    end
  end

  def create
    @playlist = Playlist.find params["playlist_id"]
    @playlist_item = @playlist.playlist_items.create(song: Song.find(params[:id]), user: User.find(session[:user_id]))
    @playlist.update_attributes(start_time: Time.now) if @playlist.playlist_items.count == 1
  end

  def upvote
    @playlist_item = PlaylistItem.find params[:id]
    @playlist_item.upvote session[:user_id]
  end

  def veto
    @playlist_item = PlaylistItem.find params[:id]
    @playlist_item.veto session[:user_id]
  end
end

app/views/playlist_items/_album.html.erb
<tr>
  <td><%= link_to "lookup", album_lookup_path(playlist_id: @playlist.id, spotify_link: album.spotify_link), remote: true, class: "btn btn-primary loadonclick"  %></td>
  <td><%= truncate(album.name , :length => 40, :omission => '...') %></td>
  <td><%= link_to "album", album.spotify_link, class: "btn" %></td>
</tr>

app/views/playlist_items/_album_table.html.erb
<table class="table" id='song_table'>
<thead>
<tr>
  <th>Select</th>
  <th>Name</th>
  <th>Link</th>
</tr>
<thead>
<tbody>
</tbody>
</table>

app/views/playlist_items/_artist.html.erb
<tr>
  <td><%= link_to "lookup", artist_lookup_path(playlist_id: @playlist.id, spotify_link: artist.spotify_link), remote: true, class: "btn btn-primary loadonclick"  %></td>
  <td><%= truncate(artist.name , :length => 40, :omission => '...') %></td>
  <td><%= link_to "artist",artist.spotify_link, class: "btn" %></td>
</tr>

app/views/playlist_items/_artist_table.html.erb
<table class="table" id='song_table'>
<thead>
<tr>
  <th>Select</th>
  <th>Name</th>
  <th>Link</th>
</tr>
<thead>
<tbody>
</tbody>
</table>

app/views/playlist_items/_form.html.erb
<div id="addSongModal" class="modal hide fade">
  <div class="modal-header">
  <h3>Search spotify</h3>
  </div>
  <div class="modal-body">
    <%= form_tag(search_path, remote: true, id: 'search_form', class: 'form-search') do |f| %>
    <%= hidden_field_tag "playlist_id", @playlist.id %>
    <div class="control-group">
      <div class="controls">
      <%= label_tag :search, "By name:", class: "control-label" %>
        <%= text_field_tag :search, nil, placeholder: "song name", class: "search-query" %>
      </div>
    </div>
    <div class="control-group">
      <div class="controls">
      <%= label_tag :artist, "or by artist:", class: "control-label" %>
        <%= text_field_tag :artist, nil, placeholder: "artist name", class: "search-query" %>
      </div>
    </div>
    <div class="control-group">
      <div class="controls">
        <%= submit_tag 'search', :class => 'btn search_button' %>
      </div>
    </div>
    <% end %>
    <p class="loading">
      <%= image_tag "spinner.gif" %>
    </p>
    <div id="results_table">
    </div>
    <div class="modal-footer">
    <a data-dismiss="modal" class="btn">Close</a>
  </div>
</div>

app/views/playlist_items/_song.html.erb
<tr>
  <td><%= link_to "add", playlist_playlist_items_path(playlist_id: @playlist,target: "#{@playlist.name}_table", id: song.id), method: 'post', remote: true, class: "btn btn-primary loadonclick" %></td>
  <td><%= truncate(song.name , :length => 40, :omission => '...') %></td>
  <td><%= seconds_to_mins song.length %></td>
  <td><%= link_to "play", song.spotify_link, class: "btn" %></td>
  <td><%= link_to song.album.name, album_lookup_path(playlist_id: @playlist.id, spotify_link: song.album.spotify_link), remote: true, class: 'loadonclick' %></td>
  <td><%= link_to song.artists.first.name, artist_lookup_path(playlist_id: @playlist.id, spotify_link: song.artists.first.spotify_link), remote: true, class: 'loadonclick' %></td>
</tr>

app/views/playlist_items/_song_table.html.erb
<table class="table" id='song_table'>
<thead>
<tr>
  <th>Select</th>
  <th>Name</th>
  <th>Length</th>
  <th>Link</th>
  <th>Album Name</th>
  <th>Artist Name</th>
</tr>
<thead>
<tbody>
</tbody>
</table>