config/routes.rb
Electune::Application.routes.draw do

  root :to => 'playlists#show', :id => '1'

  resources :users
  resources :sessions, only: [:create, :destroy]
  resources :playlists do
    get 'current', on: :member
    resources :playlist_items, :only => [:create]
  end

  match "/search" => "playlist_items#index", as: "search", via: :post
  match "/artist_lookup" => "playlist_items#artist_lookup", as: "artist_lookup", via: :get
  match "/album_lookup" => "playlist_items#album_lookup", as: "album_lookup", via: :get

  match "/playlist_items/upvote/:id" => "playlist_items#upvote", as: "upvote", via: :post
  match "/playlist_items/veto/:id" => "playlist_items#veto", as: "veto", via: :post

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/views/layouts/_messages.html.erb
<% js = js_notifications %>
<%= javascript_tag js unless js.empty? %>

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">
  <% if signed_in? %>
    <li>
    <%= link_to('Sign out', signout_path, :method=>'delete') %>
    </li>
  <% else %>
    <li>
    <%= link_to('Sign in', signin_path)  %>
    </li>
  <% end %>
  <% if signed_in? %>
    <li>
      <div class="navtext">Signed in as:</div>
    </li>
    <li>
      <%= gravatar_for(current_user) %>
    </li>
  <% else %>
    <li>
    <%= link_to('Sign up', new_user_path)  %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Electune" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>